version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 1
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "monthly"
