name: Build

on: [push]

jobs:
  build:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
      with:
        # so marceloprado/has-changed-path@v1 can detect changes
        fetch-depth: 2
    - name: token
      run: |
        set -x
        curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore"
    - name: Set up Python 3.7
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Cache virtualenv
      id: cache-venv
      uses: actions/cache@v2
      with:
        path: .venv
        key: ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-venv-${{ hashFiles('setup.py') }}
    - name: make install
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: make install
    - name: make hooks
      run: make hooks
    - name: Make and test distribution
      run: make dist test-dist
    - name: Check for version bump
      if: github.ref == 'refs/heads/main'
      uses: marceloprado/has-changed-path@v1
      id: version-bump
      with:
        paths: asu/__init__.py
    - name: Upload dist to pypi
      if: steps.version-bump.outputs.changed == 'true'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: make publish
    - name: Read version
      if: steps.version-bump.outputs.changed == 'true'
      run: echo "version=$(python setup.py --version)" >> $GITHUB_ENV
    - name: Tag commit
      if: steps.version-bump.outputs.changed == 'true'
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "${{ env.version }}"

