name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      id: setup-python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Cache virtualenv
      uses: actions/cache@v2
      with:
        path: venv
        key: ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-venv-${{ hashFiles('setup.py') }}
    - name: install
      if: steps.cache.outputs.cache-hit != 'true'
      run: make install
    - uses: pre-commit/action@v2.0.0
      with:
        extra_args: --all-files --hook-stage push
    - name: check for version bump
      if: github.ref == 'refs/heads/main'
      uses: marceloprado/has-changed-path@v1
      id: version-bump
      with:
        paths: asu/__init__.py
    - name: upload to pypi
      if: steps.version-bump.outputs.changed == 'true'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: make publish
    - name: set version
      if: steps.version-bump.outputs.changed == 'true'
      run: echo "version=$(python setup.py --version)" >> $GITHUB_ENV"
    - name: Tag commit
      if: steps.version-bump.outputs.changed == 'true'
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "${{ env.version }}"

